In [6]:
import numpy as np
import pandas as pd
from polars import head


def test(arr, block: int = 2):
    h, w = arr.shape

    print(h, w)

    h_crop = (h // block) * block
    w_crop = (w // block) * block

    print(h_crop, w_crop)

    cropped = arr[:h_crop, :w_crop]
    print(f"Cropped: {cropped}")

    reshaped = cropped.reshape(h_crop // block, block, w_crop // block, block)
    print(f"Reshaped: \n{reshaped}")

    transposed = reshaped.transpose(0, 2, 1, 3)
    print(f"Transposed: \n{transposed}")


arr = np.array([
    [0, 1, 2, 3],
    [4, 5, 6, 7],
    [8, 9, 10, 11],
    [12, 13, 14, 15]
])

print(test(arr))

4 4
4 4
Cropped: [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]
Reshaped: 
[[[[ 0  1]
   [ 2  3]]

  [[ 4  5]
   [ 6  7]]]


 [[[ 8  9]
   [10 11]]

  [[12 13]
   [14 15]]]]
Transposed: 
[[[[ 0  1]
   [ 4  5]]

  [[ 2  3]
   [ 6  7]]]


 [[[ 8  9]
   [12 13]]

  [[10 11]
   [14 15]]]]
None


In [13]:
from sqlalchemy.orm import sessionmaker
from dotenv import load_dotenv
from sqlalchemy import select, literal, func
from whatsthatfish.src.database.config import get_session_factory
from whatsthatfish.src.database.models import InatFilteredObservations

load_dotenv()
session_factory = get_session_factory()
with session_factory() as session:
    ids = session.execute(
        select(func.concat(InatFilteredObservations.photo_id, ".", InatFilteredObservations.extension))
    ).scalars().all()

print(ids[:5])


['196680.jpg', '145450.JPG', '212681.jpg', '180048.jpg', '127250.JPG']
